### ISSUE TITLE
min_pool_size does not work, not using anywhere in code

### ISSUE THREAD

**Issue by arvatoth-vcc** [mongodb/mongo-c-driver#50]
There is a variable pair: min and max_pool_size. I found in code the min_pool_size variable exists but never used anywhere. 

Expected results:
- When min_pool_size set to 10 (for example), driver has to open ten connection to mongo server, and use them when need

**Comment by samantharitter** [comment]
Hi @arvatoth-vcc, thanks for this!  If you're still interested in contributing this fix, please open a pull request against ```master,``` and we can give it a proper review.  At first look, it seems like you are missing a comparison operator in the condition for your ```while``` loop.  Also, this fix should probably use the ```mongoc_client_pool_push``` method instead of accessing the underlying queue directly.

I am going to close this issue for now, but do feel free to open a ticket in [our JIRA project](https://jira.mongodb.org/browse/CDRIVER) and a pull request if you'd like to work on this further.  Thank you!
